name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Check Docker Hub username
        run: echo "User is ${{ secrets.DOCKERHUB_USERNAME }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/obsidian-sync-couchdb:latest
